pipeline {
    agent any
    tools {
        maven 'maven'
        }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'ce8c2b00-3056-4d2b-8bf4-946d06d81ade',
                url: 'https://github.com/hsct2707/repo.git'
                }
        }
        stage ('Compile') {
            steps {
                sh 'mvn compile'
                }
            }  
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
